[pytest]
# Указываем Django settings
DJANGO_SETTINGS_MODULE = config.settings

# Какие файлы pytest считает тестами
python_files = test_*.py

# Папка с тестами
testpaths = electronics/tests

# Тихий режим вывода
addopts = -q --cov=electronics